release:
  github:
    owner: lmittmann
    name: flashbots
  draft: true
  footer: |
    **Full Changelog**: [`{{ .PreviousTag }}…{{ .Tag }}`](https://github.com/{{ .Env.GITHUB_REPOSITORY }}/compare/{{ .PreviousTag }}...{{ .Tag }})

changelog:
  sort: asc
  use: github-native

builds:
- skip: true
